### ISSUE TITLE
New Client

### ISSUE THREAD

**Issue by umgefahren** [umgefahren/server-language-benchmark#57]
There will be a new client, since the old one is very performant but very useless. Please tell me, what you want to see in the new client.

**Comment by vypxl** [comment]
Cool fancy output

**Comment by umgefahren** [comment]
I started working on the client. In order to be more flexible with benchmarking and testing plans I'm working on an option to provide a config file.
What do you think about something like this:
```yaml
general:
  totalduration: 10.0
  serverhostname: localhost
  serverport: 8080
  commandsperconn: 5
basic:
  key:
    minlen: 10
    maxlen: 1000
    alphanumeric: false
  value:
    minlen: 10
    maxlen: 1000
    alphanumeric: false
  cycleduration: -1.0
  cyclepattern: SET-GET-GET-GET-DEL
```
